### PR TITLE
FIX: Removing health_check configuration for ALB target group type

### PR DESCRIPTION
**Pull request by pablo19sc**
* Removing health_check configuration for ALB target group type.
* Updating example *target_groups* with ALB type.
* Minor updates to README.

### CODE REVIEW

**Review by taylaand — APPROVED** [review]

**Review by taylaand — APPROVED** [review]

**Review by NetDevAutomate — APPROVED** [review]

**Review by taylaand — APPROVED** [review]
Approved

**Review by NetDevAutomate — APPROVED** [review]
Approved

**Review by taylaand — APPROVED** [review]

**Review by NetDevAutomate — APPROVED** [review]

**Comment by robertdeheer** [comment]
> Approved

@pablo19sc almost there

**Review by tbulding — APPROVED** [review]

**Pull request merged**
