### PR TITLE
Updating Lambda configuration

### PR DESCRIPTION
**Pull request by pablo19sc**
- Adding support for Lambda event structure (V1 or V2) in Target Group configuration.
- Adding resource `aws_lambda_permission` when doing Lambda target group attachment.
- Moving from terratest to terraform test

### CODE REVIEW

**Review by NetDevAutomate — APPROVED** [review]
Approved

**Review by wellsiau-aws — CHANGES_REQUESTED** [review]
@pablo19sc , thanks this is looking good.

are you not planning to cut new release for this PR? I saw that the version file is up to date.

**Comment by pablo19sc** [comment]
@wellsiau-aws my bad! Updated now :)

**Review by wellsiau-aws — APPROVED** [review]

**Pull request merged**
