### PR TITLE
Update logic for healthcheck if ALB do not set.

### PR DESCRIPTION
**Pull request by jacobsims214**
Fix for Logic.
If ALB is type then do not create a health check config.

### CODE REVIEW

**Review by eduardoasantana — APPROVED** [review]

**Comment by jacobsims214** [comment]
Update on this, 
We have confirmed with this logic update the module now works without errors. 

ALB's should not pass a health check config as Targets.

**Comment by pablo19sc** [comment]
@jacobsims214 I'm getting an error in the Target Group examples - _No more than 1 "health_check" blocks are allowed_

Can you please make sure only 1 health check is created? Except ALB target (which should be none)

**Comment by wenqiglantz** [comment]
Any update on this @pablo19sc or @jacobsims214?  I am running into the same issue with ALB being the type, got error "ALB Target Group does not support health check config".  @pablo19sc, I'd appreciate it if this issue can be resolved based on the PR @jacobsims214 has already raised.

**Comment by pablo19sc** [comment]
Hi! From my side, I'm waiting from @jacobsims214 to include the fix, as with the current changes the other Target Group configurations are giving me errors. I can work directly on this, but mid-December.

**Comment by wenqiglantz** [comment]
Thanks @pablo19sc. Appreciate it if you could directly work on this and resolve this.

**Comment by robertdeheer** [comment]
@pablo19sc we would greatly appreciate it if you could provide an eta for this work. we are blocked. thanks.

**Comment by pablo19sc** [comment]
Hi! @robertdeheer. I created this PR - https://github.com/aws-ia/terraform-aws-amazon-vpc-lattice-module/pull/30 - with the proper fix (@jacobsims214 approach was close). As soon as I get a second approval I'll merge and release a new version.

**Comment by robertdeheer** [comment]
> Hi! @robertdeheer. I created this PR - #30 - with the proper fix (@jacobsims214 approach was close). As soon as I get a second approval I'll merge and release a new version.

Awesome, thanks @pablo19sc

**Comment by robertdeheer** [comment]
> > Hi! @robertdeheer. I created this PR - #30 - with the proper fix (@jacobsims214 approach was close). As soon as I get a second approval I'll merge and release a new version.
> 
> Awesome, thanks @pablo19sc

@pablo19sc is the code ready to release? Forgive me for nagging ;)

**Comment by pablo19sc** [comment]
Closing this as the fix was added in https://github.com/aws-ia/terraform-aws-amazon-vpc-lattice-module/pull/30 (https://github.com/aws-ia/terraform-aws-amazon-vpc-lattice-module/releases/tag/v0.0.3). 

@jacobsims214 thank you for your fix, I added in the Release information - even if we closed this in other PR.

**Pull request closed without merging**
