### PR TITLE
Adding AWS RAM share support (VPC Lattice service networks and services)

### PR DESCRIPTION
**Pull request by pablo19sc**
Adding support to share VPC Lattice service networks and services with AWS RAM. Added implementation code, example, test file, and updated documentation.

### CODE REVIEW

**Comment by pablo19sc** [comment]
Fixes https://github.com/aws-ia/terraform-aws-amazon-vpc-lattice-module/issues/56

**Review by NetDevAutomate — APPROVED** [review]

**Review by NetDevAutomate — APPROVED** [review]

**Review by NetDevAutomate — APPROVED** [review]
/confirm-publication

**Review by NetDevAutomate — APPROVED** [review]

**Review by NetDevAutomate — APPROVED** [review]

**Review by taylaand — APPROVED** [review]

**Review by wellsiau-aws — APPROVED** [review]
LGTM

**Pull request merged**
